##############################################################
#
# Android Security Research Lab
# Doctor Configuration
#
##############################################################

#
# Supported Ubuntu Versions
#
SUPPORTED_UBUNTU="24.04"

#
# Hardware Requirements
#
MIN_MEMORY_GB=16
RECOMMENDED_MEMORY_GB=23

MIN_DISK_GB=100
RECOMMENDED_DISK_GB=200

#
# CPU
#
RECOMMENDED_CPU_CORES=2

#
# Future
#
# ANDROID_SDK_VERSION=
# NDK_VERSION=
# CMAKE_VERSION=
#
